# Generated by Django 2.2.6 on 2020-12-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
