# Generated by Django 2.2.6 on 2021-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20210121_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link_type',
            field=models.CharField(choices=[('Youtube', 'youtube'), ('Twitter', 'twitter'), ('Вконтакте', 'vk'), ('Instagram', 'instagram'), ('Facebook', 'facebook')], max_length=10, verbose_name='Тип ссылки'),
        ),
    ]
