# Generated by Django 2.2.6 on 2021-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210128_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/profile-default.jpg', upload_to='users/avatars', verbose_name='Аватар пользователя'),
        ),
    ]
