# Generated by Django 2.2.6 on 2021-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_about_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_author',
            field=models.TextField(max_length=700, verbose_name='О себе'),
        ),
    ]
