# Generated by Django 2.2.6 on 2021-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_timestamp',
            field=models.IntegerField(default=0, help_text='Время до повторной отправки письма', verbose_name='Переотправление письма'),
        ),
    ]
