# Generated by Django 2.2.6 on 2021-02-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_email_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_timestamp',
            field=models.IntegerField(default=1614078644, help_text='Время до повторной отправки письма', verbose_name='Переотправление письма'),
        ),
    ]
