# Generated by Django 2.2.6 on 2021-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210223_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_timestamp',
            field=models.IntegerField(default=0, help_text='Время до повторной отправки письма', verbose_name='Переотправление письма'),
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
