version: '3.4'

services:
  postgres-article:
    image: postgres:12-alpine
    container_name: postgres-article
    restart: on-failure
    volumes:
      - postgres-article-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: article_db
      POSTGRES_USER: article-user
      POSTGRES_PASSWORD: articlepswd

  article-app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      target: devstage
    container_name: article-app
    environment:
      WAIT-HOSTS: postgres-article
    command: gunicorn _project_.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/home/articleweb/app
      - static-volume:/home/articleweb/app/static
      - media-volume:/home/articleweb/app/media
    expose:
      - 8000
    tty: true
    restart: on-failure
    depends_on:
      - postgres-article

  nginx:
    image: nginx:1.15-alpine
    volumes:
      - static-volume:/home/articleweb/app/static
      - media-volume:/home/articleweb/app/media      
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - article-app

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  postgres-article-data:
  static-volume:
  media-volume:
networks:
  default:
    external:
      name: articleweb-network
