version: '3.4'

services:
  postgres-article:
    image: postgres:12-alpine
    container_name: postgres-article
    restart: on-failure
    volumes:
      - postgres-article-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: article_db
      POSTGRES_USER: article-user
      POSTGRES_PASSWORD: articlepswd

  article-app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: devstage
    container_name: article-app
    environment:
      WAIT-HOSTS: postgres-article
    command: gunicorn _project_.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/home/articleweb/app
    expose:
      - 8000
    tty: true
    restart: on-failure
    depends_on:
      - postgres-article

  nginx:
    build: ./nginx
    volumes:
      - static-volume:/home/articleweb/app/static
      - media-volume:/home/articleweb/app/media
    ports:
      - 1337:80
    depends_on:
      - article-app

volumes:
  postgres-article-data:
  static-volume:
  media-volume:

networks:
  default:
    external:
      name: articleweb-network